### ISSUE TITLE
webpack configuration in order to produce .png files

### ISSUE THREAD

**Issue by gcapnias** [github1/svg-to-png-loader#1]
Hi,

Is there an example how to use svg-to-png-loader, inside a webpack.config file?

Inside the source code on src/index.js there is a reference in 'child_process'; although there is no reference in package.json about this dependency...

Thanks,
George J.

**Comment by github1** [comment]
Hi @gcapnias - I've added an example of using this in webpack config. The `child_process` dependency is a core part of the nodejs runtime so it shouldn't need to be installed separately.
