### ISSUE TITLE
target size is no longer optional

### ISSUE THREAD

**Issue by chrisdeely** [github1/svg-to-png-loader#14]
From the documentation page:
> If no size is specified, the size will be detected automatically from the svg file, and exported with the key 0x0.

However as of the latest release, with the move to the `sharp` library, the default size applied is `1x1` which results in the creation of 1x1 png files rather than converting the images at their natural dimensions.

This could be avoided by skipping the `resize()` call if the size parameters are omitted.

**Comment by github1** [comment]
Thanks for the suggestion, this is fixed in 4.0.1
